
networks:
  default:
    external: true
    name: dev-local

services:
  opensearch:
    image: opensearchproject/opensearch:$VERSION
    container_name: opensearch
    hostname: opensearch
    environment:
      - "discovery.type=single-node"
      - "plugins.security.disabled=true"
    ports:
      - "9200:9200"

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:$VERSION
    container_name: opensearch-dashboards
    hostname: opensearch-dashboards
    ports:
      - "5601:5601"
    environment:
      - "OPENSEARCH_HOSTS=http://opensearch:9200"
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    depends_on:
      - opensearch
